# https://render.com/docs/blueprint-spec
version: "1"

databases:
  - name: poker-pairs-db
    plan: free
    region: oregon
    postgresMajorVersion: "16"
    databaseName: poker_pairs
    user: poker_pairs

services:
  - type: web
    name: poker-pairs
    runtime: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poker-pairs-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: STATIC_FOLDER
        value: /app/static
