# https://render.com/docs/blueprint-spec
version: "1"

services:
  - type: web
    name: poker-pairs
    runtime: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: sqlite:////tmp/poker_pairs.db
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: STATIC_FOLDER
        value: /app/static
