# https://render.com/docs/blueprint-spec
version: "1"

services:
  - type: web
    name: royal-match-poker
    runtime: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: sqlite:////tmp/poker_pairs.db
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: STATIC_FOLDER
        value: /app/static
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
